import { IPassengerDetails, IPassengers } from './types'

export const mockPassengerDetails: IPassengerDetails = {
  login: '12',
  id: 7690572,
  node_id: 'MDQ6VXNlcjc2OTA1NzI=',
  avatar_url: 'https://avatars.githubusercontent.com/u/7690572?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/12',
  html_url: 'https://github.com/12',
  followers_url: 'https://api.github.com/users/12/followers',
  following_url: 'https://api.github.com/users/12/following{/other_user}',
  gists_url: 'https://api.github.com/users/12/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/12/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/12/subscriptions',
  organizations_url: 'https://api.github.com/users/12/orgs',
  repos_url: 'https://api.github.com/users/12/repos',
  events_url: 'https://api.github.com/users/12/events{/privacy}',
  received_events_url: 'https://api.github.com/users/12/received_events',
  type: 'User',
  site_admin: false,
  name: 'Rhys Hellyar',
  company: '@starlingbank',
  blog: '',
  location: 'London',
  email: null,
  hireable: true,
  bio: '@starlingbank, previously @bbc ',
  twitter_username: null,
  public_repos: 8,
  public_gists: 10,
  followers: 2,
  following: 0,
  created_at: '2014-05-24T19:57:45Z',
  updated_at: '2021-12-26T15:56:17Z',
}

export const mockPassgers: IPassengers = {
  totalPassengers: 28030,
  totalPages: 2803,
  data: [
    {
      _id: '5ff5b02d522101e10fa9a412',
      name: 'Percy Townsend',
      trips: 250,
      airline: [
        {
          id: 5,
          name: 'Eva Air',
          country: 'Taiwan',
          logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/ed/EVA_Air_logo.svg/250px-EVA_Air_logo.svg.png',
          slogan: 'Sharing the World, Flying Together',
          head_quaters: '376, Hsin-Nan Rd., Sec. 1, Luzhu, Taoyuan City, Taiwan',
          website: 'www.evaair.com',
          established: '1989',
        },
      ],
    },
  ],
}
