export const mockPassengerDetails = {
  login: '12',
  id: 7690572,
  node_id: 'MDQ6VXNlcjc2OTA1NzI=',
  avatar_url: 'https://avatars.githubusercontent.com/u/7690572?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/12',
  html_url: 'https://github.com/12',
  followers_url: 'https://api.github.com/users/12/followers',
  following_url: 'https://api.github.com/users/12/following{/other_user}',
  gists_url: 'https://api.github.com/users/12/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/12/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/12/subscriptions',
  organizations_url: 'https://api.github.com/users/12/orgs',
  repos_url: 'https://api.github.com/users/12/repos',
  events_url: 'https://api.github.com/users/12/events{/privacy}',
  received_events_url: 'https://api.github.com/users/12/received_events',
  type: 'User',
  site_admin: false,
  name: 'Rhys Hellyar',
  company: '@starlingbank',
  blog: '',
  location: 'London',
  email: null,
  hireable: true,
  bio: '@starlingbank, previously @bbc ',
  twitter_username: null,
  public_repos: 8,
  public_gists: 10,
  followers: 2,
  following: 0,
  created_at: '2014-05-24T19:57:45Z',
  updated_at: '2021-12-26T15:56:17Z',
}
